### ISSUE TITLE
Build error in latest version

### ISSUE THREAD

**Issue by Vortec4800** [AnthonyMDev/AmazonS3RequestManager#10]
I'm getting this build error:

AmazonS3RequestManager/AmazonS3RequestManager.h:29:9: Include of non-modular header inside framework module 'AmazonS3RequestManager.AmazonS3RequestManager'

when compiling the latest version installed using Cocoapods. This is using Xcode 7.1 beta 3 targeting iOS 9.1, in case it's an Xcode change.

It seems to not like the
# import <AmazonS3RequestManager/AmazonS3SignatureHelpers.h>

line in the umbrella header file. Perhaps the Obj-C files aren't being added to the module map or something?

May be a bit annoying, but converting this file to Swift might be a solution.

**Comment by Vortec4800** [comment]
So quick update, I changed the line in the `AmazonS3RequestManager.h` file from 

#import <AmazonS3RequestManager/AmazonS3SignatureHelpers.h>

to

#import "AmazonS3SignatureHelpers.h"

which fixed the problem and everything built successfully. I'm unsure if this is a "real" fix or if this is just getting everything to work, but not the root cause. Either way it's a fix for the time being.

**Comment by AnthonyMDev** [comment]
@Vortec4800 Thank you for bringing this to my attention, and for the possible solution. I will look into this today and see if I can re-create. I haven't experienced this problem myself yet.

`AmazonS3SignatureHelpers` can't really be converted to swift easily, since it uses some C libraries that could not be bridged into the swift runtime.

**Comment by AnthonyMDev** [comment]
@Vortec4800 This has been fixed using your provided solution in version 0.9.0. Thank you!

Please let me know if this issue still exists for you in 0.9.0.
