### ISSUE TITLE
Spaces (or other special chars) in a filename

### ISSUE THREAD

**Issue by petraalm** [AnthonyMDev/AmazonS3RequestManager#12]
I've noticed that uploading files containing spaces or other special characters (ie. foreign language characters) in the name always fails with 403. Anybody else facing the same issue?
`URLByAppendingPathComponent` in `amazonURLRequest` method returns percent-encoded url so what could be the problem then?

**Comment by AnthonyMDev** [comment]
Hmm that's odd. Just confirming, you are talking about the `destinationPath` for the upload having spaces or special characters in it.

It may just be that Amazon S3 does not support those characters in their file paths. If that is the case, the only thing I can do about it is to add a note on it to the documentation. I'll look into this and see if this is an Amazon thing or a problem with the library.

Thanks!

**Comment by AnthonyMDev** [comment]
What special characters are you using specifically? Some special characters are supported, but not all it seems.

Object names:

> The following character sets are generally safe for use in key names:
> - Alphanumeric characters [0-9a-zA-Z]
> - Special characters !, -, _, ., *, ', (, and )

Bucket names:

> Bucket names must be a series of one or more labels. Adjacent labels are separated by a single period (.). Bucket names can contain lowercase letters, numbers, and hyphens. Each label must start and end with a lowercase letter or a number.

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by petraalm** [comment]
Foreign language characters e.g. šđčćž. I was able to make a workaround by using id instead of a filename in the destination path. However, I still dont understand why the problem happens. In the guidelines you posted it says using any UTF-8 character should be ok, which I believe is true because if I do the uploading to s3 on the server side (using [paperclip](https://github.com/thoughtbot/paperclip)) it works. Paperclip substitutes spaces with underscore tho, but foreign language characters get percent encoded.
Were you able to reproduce the issue?
