### ISSUE TITLE
Allow for copying objects

### ISSUE THREAD

**Issue by sebromero** [AnthonyMDev/AmazonS3RequestManager#26]
S3 allows files to be copied from one location to another. AmazonS3RequestManager currently doesn't support that. 
See: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html

**Comment by AnthonyMDev** [comment]
Thanks for making a PR for this! I'll get this pulled in ASAP. These changes are going to be dependent upon the refactor being done to #23, so as soon as that is finished, this will be pulled in.
