### ISSUE TITLE
Add parameter options to listBucketObjects()

### ISSUE THREAD

**Issue by AnthonyMDev** [AnthonyMDev/AmazonS3RequestManager#28]
We should have parameters to set all of the parameters from the REST API for the `listBucketObjects()` request method.
- [ ] Add parameters to function
- [ ] Add example for `listBucketObjects()' to`README`

For parameters see: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html

**Comment by sebromero** [comment]
I agree, using `subresouce` isn't the right way to do it. I didn't really understand the notion of subresources until now. We should add the missing parameter doc to `amazonURLRequest` to make that clear.

**Comment by AnthonyMDev** [comment]
Didn't realize that was missing! Documentation has been added for that parameter. Thanks.
