### ISSUE TITLE
ACL for file uploads

### ISSUE THREAD

**Issue by freak4pc** [AnthonyMDev/AmazonS3RequestManager#3]
How would I go about setting the uploaded file's ACL to Public ? 

Thanks.

**Comment by AnthonyMDev** [comment]
@freak4pc I haven't implemented any APIs for editing a file's permissions or other information yet. It might be possible to set it with a parameter, let me look at the APIs and get back to you. If not, I'll try adding some new APIs for this today.

Thanks for the question!

**Comment by AnthonyMDev** [comment]
I've started work on developing this. I hope to have it fully implemented by the end of the weekend.

@freak4pc Do you need to use this by a specific date?

**Comment by freak4pc** [comment]
Hey, Thanks for answering @AnthonyMDev 
I actually overridden my issue by setting a public Bucket Policy so I'm good for now. No worry :) 

In a different note, did you think about making the manager a background upload manager ? 
![e3b5e94f-0284-4824-ae4d-c3a96f286fa6](https://cloud.githubusercontent.com/assets/605076/8072166/09d5a510-0f1b-11e5-9867-91537270fabd.jpg)

**Comment by AnthonyMDev** [comment]
@freak4pc 
Okay, that should work. I'm still going to go ahead and finish this feature set up.

I haven't looked into that yet. I'll look at the benefits of it. I think it would be best to allow the user to set the configuration, so maybe I'll make that happen.

Are you actually using this repository at the moment? I haven't gotten any confirmation that anyone besides myself is even using this right now.

**Comment by AnthonyMDev** [comment]
This feature should be working on the `acl` branch with `PUT` requests currently. I'm going to be looking into implementing ACL on other request methods, and creating methods that allow you to get and edit the ACL of an object and bucket at some point this week.

I'll also be adding more documentation to how the ACL system works and adding it to the `README`.

**Comment by freak4pc** [comment]
Yeah @AnthonyMDev , I'm absolutely using it. Really great lib and an awesome time saver for me. 

I agree that being able to configure the client to perform in a background session would be very beneficial.

**Comment by AnthonyMDev** [comment]
That's great to hear!

Thanks for the suggestions. I'll look into the rest of this soon.

**Comment by AnthonyMDev** [comment]
All functionality has been implemented, unit tested, and documented. I'll be updating the `README` with new examples tomorrow and pushing out a new version of the CocoaPod.

**Comment by freak4pc** [comment]
Awesome :) Will check it out.

**Comment by AnthonyMDev** [comment]
@freak4pc In response to your suggestion for using a background upload manager configuration:
Right now, the request manager is being set, by default, to the `Alamofire.sharedInstance`. The `requestManager` variable is public though, and can be set to another instance of `Alamofire.Manager`.

To use a background upload manager, you can just create a new `Alamofire.Manager` with the desired configuration and set it to the `requestManager` variable. It will then be used for all requests.

Currently, I feel like leaving the `sharedInstance` as the default is best, but if you can give me a compelling reason why creating a background upload manager as the default request manager is better, I'm all ears!

**Comment by AnthonyMDev** [comment]
Also, this feature has been completed and version `0.5.0` has been released to include ACL APIs
