### ISSUE TITLE
xcode 8 beta 2 fails to compile 

### ISSUE THREAD

**Issue by romk1n** [AnthonyMDev/AmazonS3RequestManager#33]
```
AmazonS3RequestSerializer.swift:127:23: error: value of optional type 'NSURL?' not unwrapped; did you mean to use '!' or '?'?
            url = url.URLByAppendingPathComponent(path)
                      ^
                                                       !
AmazonS3RequestSerializer.swift:224:34: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
            let URLString = self.absoluteString.stringByAppendingString("?\(subresource)")
                                 ^
                                               !
```

**Comment by AnthonyMDev** [comment]
Swift 3 support has not yet been implemented. #32 covers this issue. It will be implemented before Swift 3 GM is released. If you would like to make a PR to fix these issues, please feel free to do so.

**Comment by romk1n** [comment]
Well. The problem is in swift 2.3

**Comment by AnthonyMDev** [comment]
@romk1n Are you sure? Swift 2.3 should compile that code just fine. Xcode 8 by default uses Swift 3, so unless you have downloaded the Swift 2.3 toolchain and manually set Xcode to use it, you will be using Swift 3.

Please confirm that you are using Swift 2.3 and I'll look into this.

**Comment by romk1n** [comment]
@AnthonyMDev i have modified all the pods to set legacy swift and it didn't compile. i will double check again in a few days and will report again. Thanks.

**Comment by AnthonyMDev** [comment]
@romk1n I'm not exactly sure what you mean about setting the pods to use legacy swift.

The version of swift that it being compiled for is set by Xcode. I don't believe that setting any configuration in the pods will change that. If you can explain to me what you are doing a little more I can try to provide more support. Thanks.
