### ISSUE TITLE
S3ObjectMetaData initializer crashes

### ISSUE THREAD

**Issue by sebromero** [AnthonyMDev/AmazonS3RequestManager#36]
When fetching meta data for an S3 object the `S3ObjectMetaData` initializer crashes with a bad access exception. This is most likely due to the `representation` parameter that is of typ `Any`. This apparently leads to a memory problem because the representation object won't be retained until the end of the initializer.

**Comment by AnthonyMDev** [comment]
@sbhklr I've pushed some changes to `develop` that I believe will fix this issue. I am trying a different approach to what you've done in #37.

There is now a `responseS3MetaData` serialization method that can be used.

I was unable to reproduce the crash. Could you confirm if this fixes the crash you are experiencing or not?

Thanks.

**Comment by sebromero** [comment]
Your changes indeed fix it. A couple of notes:
- Shouldn't the initializer of `S3ObjectMetaData` return nil in case there are no headers available?
- Shouldn't the completion handler be of type `completionHandler: Response<S3ObjectMetaData, NSError> -> Void` because `Result.value` already returns an optional type. Otherwise I'd need to call it like `if let metaData = response.result.value?!.metaData {}` Suggestion:

```
public func responseS3MetaData(completionHandler: Response<S3ObjectMetaData, NSError> -> Void) -> Self {
    return response(responseSerializer: Request.s3MetaDataResponseSerializer(), completionHandler: completionHandler)
}

static func s3MetaDataResponseSerializer() -> ResponseSerializer<S3ObjectMetaData, NSError> {
    return ResponseSerializer { request, response, data, error in
        guard error == nil else { return .Failure(error!) }

        guard let response = response, metaData = S3ObjectMetaData(response: response) else {
            let failureReason = "No response data was found."
            let error = Error.errorWithCode(.DataSerializationFailed, failureReason: failureReason)
            return .Failure(error)
        }

        return .Success(metaData)
    }
}
```

**Comment by AnthonyMDev** [comment]
Glad to hear this fixed the issue.

I'm sort of alright with the meta data being empty, but I can see your argument. I'll make that change as well. Hold tight. New version on the way.

I agree with your second point. I'm making a change right now to fix this. I'm also doing the same thing with the data serializer currently, so I'm going to fix that. This will cause minor API breaking changes.

**Comment by sebromero** [comment]
👍 Alrighty. I'll update the PRs accordingly.

**Comment by AnthonyMDev** [comment]
Pushing the new version right now. Thanks for your comments and your initial PR on this. If the new version does not fix the issue, please feel free to re-open this issue.
