### ISSUE TITLE
please lower spec dependency to ios 8

### ISSUE THREAD

**Issue by romk1n** [AnthonyMDev/AmazonS3RequestManager#46]
we still need to support ios 8 devices, there shouldn't be anything which prevents this running on ios 8 right ?

**Comment by AnthonyMDev** [comment]
`Alamofire` no longer supports iOS 8. Since this library is an Alamofire serializer, it is dependent upon that unfortunately.

**Comment by romk1n** [comment]
but can't you use alamofire 3.5 ?

**Comment by AnthonyMDev** [comment]
Not for Swift 3. Alamofire 3.5 was pre Swift 3 from my understanding. If that assumption is wrong, then we can consider it. 

Otherwise, if this is something you need, you're going to need to fork Alamofire 3.5 and convert it to Swift 3 then you can fork this repo and build a version that supports 8.0

**Comment by u10int** [comment]
Can this issue be reopened and the library updated to support iOS 8 again for a 1.0.5 release? As of Alamofire 4.1.0, iOS 8 is now supported again: https://github.com/Alamofire/Alamofire/issues?utf8=✓&q=milestone%3A4.1.0

**Comment by AnthonyMDev** [comment]
Yes that seems doable. I am very ill right now, so I don't know when I'll get to this. But if you need it soon, I would be willing to take a look at a PR and push a new version.

**Comment by AnthonyMDev** [comment]
@jettf If you're looking for more github contributions this should be a simple one! ;)

**Comment by u10int** [comment]
Went ahead and setup a PR on the develop branch since it was a simple adjustment: https://github.com/AnthonyMDev/AmazonS3RequestManager/pull/56

**Comment by AnthonyMDev** [comment]
`1.0.5` has been pushed with iOS `8.0` support!

**Comment by AnthonyMDev** [comment]
Thanks for your help on this @u10int
