### ISSUE TITLE
Update `download` example in Readme

### ISSUE THREAD

**Issue by phlippieb** [AnthonyMDev/AmazonS3RequestManager#52]
The Readme provides the following example for saving objects to file:

``` swift
let destination: NSURL = FileManager.defaultManager().URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]
amazonS3Manager.download(at: "myFolder/fileName.jpg", to: destination)
```

This code doesn't compile in Swift 3. The file manager API is outdated, and it seems that the `download` method does not accept an NSURL as its `to:` parameter. Please update with a working example.

Been using this library for a while and really like it. Migrating to Swift 3 is just a PITA in general. Cheers!

**Comment by AnthonyMDev** [comment]
Thanks for the kind words and the heads up! I
l'll get to this soon.

**Comment by saqibomer** [comment]
Any update on this issue?

**Comment by AnthonyMDev** [comment]
This has been fixed. The `README` will now show the correct way to download files using the latest version of `Alamofire`.

**Comment by phlippieb** [comment]
@AnthonyMDev Awesome! Thanks!
