### ISSUE TITLE
Issue for Alamofire 4.0.1

### ISSUE THREAD

**Issue by saqibomer** [AnthonyMDev/AmazonS3RequestManager#53]
I am getting error "Use of undeclared type Response" when trying to access bucket files. Is it compatible with Alamofire 4.0.1?
Great work btw.

**Comment by AnthonyMDev** [comment]
Thanks for the heads up. I'll look into this today!

**Comment by AnthonyMDev** [comment]
@saqibomer To confirm, is this a build error, or is this occuring at runtime? Also, are you trying to use Alamofire `4.0.1` or `4.1.0`. The newest version is `4.1.0` so I just wanted to confirm that wasn't a typo.

**Comment by saqibomer** [comment]
It is a build error. My environment is: Swift 3, Alamofire 4.0.1, Xcode 8.1. 
Error: "Use of undeclared type 'Response'" 
`amazonS3Manager.listBucketObjects().responseS3Object { (response: Response < S3BucketObjectList, NSError>) in`

```
        if let files = response.result.value?.files {
            for file in files {
                print(file.path)
            }
        }
    }`
```

 [For your reference:](https://github.com/Alamofire/Alamofire/issues/1535)

**Comment by AnthonyMDev** [comment]
Is there a reason why you haven't updated to `Alamofire 4.1.0`? The library is building just fine for me against that version.

**Comment by saqibomer** [comment]
I have updated to Alamofire 4.1.0. But stil got same error. Removing `Response<S3BucketObjectList, NSError>` fixed issue.

**Comment by AnthonyMDev** [comment]
Okay I'll look Into this more Monday morning!

**Comment by AnthonyMDev** [comment]
@saqibomer Can you confirm the version of this library you are using? Version `1.0.1` and up are using the new `DataResponse` from `Alamofire`.

**Comment by saqibomer** [comment]
Here are versions which I am using
`- Alamofire (4.1.0)`
`- AmazonS3RequestManager (1.0.4)`

**Comment by AnthonyMDev** [comment]
```swift
amazonS3Manager.listBucketObjects().responseS3Object { (response: Response < S3BucketObjectList, NSError>) in

        if let files = response.result.value?.files {
            for file in files {
                print(file.path)
            }
        }
    }
```

In this code you need to change `Response` to `DataResponse`
