### ISSUE TITLE
Swift 2.3 release

### ISSUE THREAD

**Issue by sebromero** [AnthonyMDev/AmazonS3RequestManager#58]
A Swift 2.3 release would be very much appreciated, since currently the absence of it breaks my whole build chain. My custom pod has a dependency on AmazonS3RequestManager and other frameworks but I cannot use Swift 3 yet because not all of the other frameworks support that yet.

**Comment by sebromero** [comment]
What about a 1.0.0-swift2-3 release? I don't know if this is a valid version specifier though.

**Comment by 646b** [comment]
I've tried to use this version `pod 'AmazonS3RequestManager', '= 1.0.0'` but I'm getting compiler errors (see https://www.dropbox.com/s/18nzxovmt71ketk/Screenshot%202017-01-10%2013.01.42.png?dl=0)

**Comment by sebromero** [comment]
@dkalachov You can do the following:
`pod 'AmazonS3RequestManager', :git => "https://github.com/AnthonyMDev/AmazonS3RequestManager.git", :branch => 'swift-2.3'`
However, this doesn't work for me as I'm creating a custom pod that has AmazonS3RequestManager as a dependency and the linting process fails because I cannot use a custom pod branch for linting.

**Comment by AnthonyMDev** [comment]
@sbhklr I'll release a pod version for you. No problem.

Didn't realize many people were still using Swift 2.3 at this point.

**Comment by AnthonyMDev** [comment]
Pod version `1.0.0-swift2-3` has been pushed!

**Comment by AnthonyMDev** [comment]
@sbhklr If you have a public CocoaPod that uses this library as a dependency, I'd love to link to it in the README. Let me know!

**Comment by sebromero** [comment]
@AnthonyMDev It's a private pod unfortunately. I'll let you know when I use it for a public one.
