### ISSUE TITLE
Swift 4 support.

### ISSUE THREAD

**Issue by WesleyBuck** [AnthonyMDev/AmazonS3RequestManager#62]
SWXMLHash needs to be updated to v4.1.0 to support swift 4

Removed Sequence from XMLIndexer to avoid a conflict with the element property coming in Swift 4

**Comment by WesleyBuck** [comment]
Pull Request for change #63

**Comment by AnthonyMDev** [comment]
PR was previously merged. I'm going to finish Xcode 9 and Swift 4 support this week hopefully. Closing this issue. Thanks for the help.
