### ISSUE TITLE
Swift 2.0 and Alamofire 2.0

### ISSUE THREAD

**Issue by freak4pc** [AnthonyMDev/AmazonS3RequestManager#9]
Is there any reason the Swift 2 version is targeting Alamofire 1.3 instead of 2.0 ?

**Comment by AnthonyMDev** [comment]
The `swift-2.0` version was created before Alamofire `2.0` was released. The library needs to be migrated over to use Alamofire `2.0`. I will likely do this in the next few days.

**Comment by AnthonyMDev** [comment]
This has been completed. the `swift-2.0` branch now uses `Alamofire 2.0`
